import { Language } from "./types";

export const UI_LABELS: Record<Language, any> = {
  en: {
    title: "Daf Rabbi",
    subtitle: "Study Gemara and Torah with an Orthodox Rabbi AI",
    selectLanguage: "Choose your study language",
    uploadPrompt: "Drag & drop a Gemara page, other Jewish book (JPG, PNG, PDF), or click to select",
    cameraPrompt: "Use Camera",
    analyzing: "The Rabbi is reviewing the sacred text...",
    askQuestion: "Ask the Rabbi a question...",
    reset: "Start New Study",
    error: "Forgive me, something went wrong.",
    history: "Study History",
    send: "Send",
    back: "Back",
    loginTitle: "Enter the Study Hall",
    loginSubtitle: "Sign in with Google to save your study sessions and continue your learning from any device.",
    loginButton: "Sign in with Google",
    loadingHistory: "Retrieving your studies...",
    noHistory: "No saved studies found. Start your first one above!",
    logout: "Sign Out",
    repository: "My Study Repository",
    repositoryTitle: "Your Personal Library",
    repositorySubtitle: "All your past encounters with holy texts, preserved for your growth.",
    delete: "Delete",
  },
  pt: {
    title: "Daf Rabbi",
    subtitle: "Estude Gemara e Torá com uma IA de Rabino Ortodoxo",
    selectLanguage: "Escolha seu idioma de estudo",
    uploadPrompt: "Arraste e solte uma página da Gemara, outro livro judaico (JPG, PNG, PDF), ou clique para selecionar",
    cameraPrompt: "Usar Câmera",
    analyzing: "O Rabino está revisando o texto sagrado...",
    askQuestion: "Faça uma pergunta ao Rabino...",
    reset: "Iniciar Novo Estudo",
    error: "Perdoe-me, algo deu errado.",
    history: "Histórico de Estudos",
    send: "Enviar",
    back: "Voltar",
    loginTitle: "Entre no Salão de Estudos",
    loginSubtitle: "Faça login com o Google para salvar suas sessões de estudo e continuar seu aprendizado de qualquer dispositivo.",
    loginButton: "Entrar com Google",
    loadingHistory: "Recuperando seus estudos...",
    noHistory: "Nenhum estudo salvo encontrado. Comece seu primeiro acima!",
    logout: "Sair",
    repository: "Meu Repositório de Estudos",
    repositoryTitle: "Sua Biblioteca Pessoal",
    repositorySubtitle: "Todos os seus encontros passados com textos sagrados, preservados para o seu crescimento.",
    delete: "Excluir",
  },
  es: {
    title: "Daf Rabbi",
    subtitle: "Estudia Guemará y Torá con una IA de Rabino Ortodoxo",
    selectLanguage: "Elige tu idioma de estudio",
    uploadPrompt: "Arrastra y suelta una página de Guemará, otro libro judío (JPG, PNG, PDF), o haz clic para seleccionar",
    cameraPrompt: "Usar Cámara",
    analyzing: "El Rabino está revisando el texto sagrado...",
    askQuestion: "Haz una pregunta al Rabino...",
    reset: "Iniciar Nuevo Estudio",
    error: "Perdóneme, algo salió mal.",
    history: "Historial de Estudios",
    send: "Enviar",
    back: "Volver",
    loginTitle: "Ingresar al Salón de Estudios",
    loginSubtitle: "Inicia sesión con Google para guardar tus sesiones de estudio y continuar tu aprendizaje desde cualquier dispositivo.",
    loginButton: "Entrar con Google",
    loadingHistory: "Recuperando tus estudios...",
    noHistory: "No se encontraron estudios guardados. ¡Empieza el primero arriba!",
    logout: "Cerrar Sesión",
    repository: "Mi Repositorio de Estudios",
    repositoryTitle: "Tu Biblioteca Personal",
    repositorySubtitle: "Todos tus encuentros pasados com textos sagrados, preservados para tu crecimiento.",
    delete: "Eliminar",
  },
  fr: {
    title: "Daf Rabbi",
    subtitle: "Étudiez la Guemara et la Torah avec une IA de Rabbin Orthodoxe",
    selectLanguage: "Choisissez votre langue d'étude",
    uploadPrompt: "Glissez-déposez une page de la Guemara, un autre livre juif (JPG, PNG, PDF), ou cliquez pour sélectionner",
    cameraPrompt: "Utiliser la Caméra",
    analyzing: "Le Rabbin examine le texte sacré...",
    askQuestion: "Posez une question au Rabbin...",
    reset: "Commencer une nouvelle étude",
    error: "Pardonnez-moi, quelque chose s'est mal passé.",
    history: "Historique d'Étude",
    send: "Envoyer",
    back: "Retour",
    loginTitle: "Entrer dans la Salle d'Étude",
    loginSubtitle: "Connectez-vous avec Google pour sauvegarder vos sessions d'étude et continuer votre apprentissage sur n'importe quel appareil.",
    loginButton: "Se connecter avec Google",
    loadingHistory: "Récupération de vos études...",
    noHistory: "Aucune étude sauvegardée. Commencez votre première étude ci-dessus !",
    logout: "Se déconnecter",
    repository: "Mon Répertoire d'Études",
    repositoryTitle: "Votre Bibliothèque Personnelle",
    repositorySubtitle: "Toutes vos rencontres passées avec des textes sacrés, préservées pour votre croissance.",
    delete: "Supprimer",
  },
  ru: {
    title: "Daf Rabbi",
    subtitle: "Изучайте Гемару и Тору с ИИ Православного Раввина",
    selectLanguage: "Выберите язык обучения",
    uploadPrompt: "Перетащите страницу Гемары, другую еврейскую книгу (JPG, PNG, PDF) или нажмите, чтобы выбрать",
    cameraPrompt: "Использовать камеру",
    analyzing: "Раввин изучает священный текст...",
    askQuestion: "Задайте вопрос раввину...",
    reset: "Начать новое изучение",
    error: "Простите, что-то пошло не так.",
    history: "История обучения",
    send: "Отправить",
    back: "Назад",
    loginTitle: "Войдите в учебный зал",
    loginSubtitle: "Войдите через Google, чтобы сохранять свои учебные сессии и продолжать обучение с любого устройства.",
    loginButton: "Войти через Google",
    loadingHistory: "Загрузка ваших исследований...",
    noHistory: "Сохраненных исследований не найдено. Начните свое первое исследование выше!",
    logout: "Выйти",
    repository: "Мой репозиторий исследований",
    repositoryTitle: "Ваша личная библиотека",
    repositorySubtitle: "Все ваши прошлые встречи со священными текстами, сохраненные для вашего роста.",
    delete: "Удалить",
  },
};
