import { Language } from "./types";

export const UI_LABELS: Record<Language, any> = {
  en: {
    title: "Daf Rabbi",
    subtitle: "Study Gemara and Torah with an Orthodox Rabbi AI",
    selectLanguage: "Choose your study language",
    uploadPrompt: "Drag & drop a Gemara page, other Jewish book (JPG, PNG, PDF), or click to select",
    cameraPrompt: "Use Camera",
    analyzing: "The Rabbi is reviewing the sacred text...",
    askQuestion: "Ask the Rabbi a question...",
    reset: "Start New Study",
    error: "Forgive me, something went wrong.",
    history: "Study Sessions",
    send: "Send",
    back: "Back",
  },
  pt: {
    title: "Daf Rabbi",
    subtitle: "Estude Gemara e Torá com uma IA de Rabino Ortodoxo",
    selectLanguage: "Escolha seu idioma de estudo",
    uploadPrompt: "Arraste e solte uma página da Gemara, outro livro judaico (JPG, PNG, PDF), ou clique para selecionar",
    cameraPrompt: "Usar Câmera",
    analyzing: "O Rabino está revisando o texto sagrado...",
    askQuestion: "Faça uma pergunta ao Rabino...",
    reset: "Iniciar Novo Estudo",
    error: "Perdoe-me, algo deu errado.",
    history: "Sessões de Estudo",
    send: "Enviar",
    back: "Voltar",
  },
  es: {
    title: "Daf Rabbi",
    subtitle: "Estudia Guemará y Torá con una IA de Rabino Ortodoxo",
    selectLanguage: "Elige tu idioma de estudio",
    uploadPrompt: "Arrastra y suelta una página de Guemará, otro libro judío (JPG, PNG, PDF), o haz clic para seleccionar",
    cameraPrompt: "Usar Cámara",
    analyzing: "El Rabino está revisando el texto sagrado...",
    askQuestion: "Haz una pregunta al Rabino...",
    reset: "Iniciar Nuevo Estudio",
    error: "Perdóneme, algo salió mal.",
    history: "Sesiones de Estudio",
    send: "Enviar",
    back: "Volver",
  },
  fr: {
    title: "Daf Rabbi",
    subtitle: "Étudiez la Guemara et la Torah avec une IA de Rabbin Orthodoxe",
    selectLanguage: "Choisissez votre langue d'étude",
    uploadPrompt: "Glissez-déposez une page de la Guemara, un autre livre juif (JPG, PNG, PDF), ou cliquez pour sélectionner",
    cameraPrompt: "Utiliser la Caméra",
    analyzing: "Le Rabbin examine le texte sacré...",
    askQuestion: "Posez une question au Rabbin...",
    reset: "Commencer une nouvelle étude",
    error: "Pardonnez-moi, quelque chose s'est mal passé.",
    history: "Sessions d'Étude",
    send: "Envoyer",
    back: "Retour",
  },
  ru: {
    title: "Daf Rabbi",
    subtitle: "Изучайте Гемару и Тору с ИИ Православного Раввина",
    selectLanguage: "Выберите язык обучения",
    uploadPrompt: "Перетащите страницу Гемары, другую еврейскую книгу (JPG, PNG, PDF) или нажмите, чтобы выбрать",
    cameraPrompt: "Использовать камеру",
    analyzing: "Раввин изучает священный текст...",
    askQuestion: "Задайте вопрос раввину...",
    reset: "Начать новое изучение",
    error: "Простите, что-то пошло не так.",
    history: "Учебные сессии",
    send: "Отправить",
    back: "Назад",
  },
};
